[package]
name = "portreaper"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.0", features = ["derive"] }
is-terminal = "0.4.17"
owo-colors = { version = "4.3.0", features = ["supports-colors"] }
quick-xml = { version = "0.39.2", features = ["serialize"] }
regex = "1.12.3"
sanitize-filename = "0.6.0"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
